name: Copycat Action
on:
# Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
jobs:
  copy-master:
    name: 'Copy contracts'
    runs-on: ubuntu-latest
    steps:
      - uses: alexroan/copycat-action
        with:
          personal_token: ${{ secrets.DESTINATION_TOKEN }}
          src_path: contracts/.
          dst_path: output/
          dst_owner: alexroan
          dst_repo_name: copycat-output
          src_branch: master
          dst_branch: master
